---
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

# kubelet fails even if ansible_swaptotal_mb = 0
- name: check swap
  command: /sbin/swapon -s
  register: swapon
  changed_when: no
- name: Disable swap
  command: /sbin/swapoff -a
  when: 
    - not ansible_check_mode
    - swapon.stdout
# Fix derived from: https://github.com/kubernetes-sigs/kubespray/issues/4967#issuecomment-510604422
