all:
  hosts:
    node1:
      ansible_host: 10.10.10.10
      ip: 10.10.10.10
      access_ip: 10.10.10.10
  children:
    packet:
      hosts:
        node1:
      vars:
        ansible_user: root
    kube-master:
      hosts:
        node1:
          cluster_id: "akash-provider"
    kube-node:
      hosts:
        node1:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
